### ISSUE TITLE
(2022.09.29) Regarding the runtime error

### ISSUE THREAD

**Issue by deepkyu** [deepkyu/ml-talking-face#1]
For who visit the Hugging Face Spaces,

The core part of the demonstration has been working on the AWS instance of MINDsLab, and I found that it can’t connect to the instance now. **I want to fix this issue, but I’m sorry to say that I left the company last week.** I’ve contacted the company, but it takes some time to restore the session. If you’re in a hurry, please send the e-mail directly to MINDsLab (hello@mindslab.ai).

**Whatever the reason, I’m sorry again. Hope you understand.**

This issue clones from the Hugging Face Spaces [ml-talking-face#10](https://huggingface.co/spaces/CVPR/ml-talking-face/discussions/10).

**Comment by deepkyu** [comment]
I'll close the issue when it works.

**Comment by datased2019** [comment]
Dear deepkyu, thanks for your remind. Is there any way that we could deploy it locally to run? Thx.

**Comment by deepkyu** [comment]
@datased2019 
I think it is not that related to this issue, so I made a new ticket #2. Hope you understand.

**Comment by deepkyu** [comment]
Guys, I restored the Hugging Face Spaces, and it works now.
I contacted the former company, and they recognized how it is important this demo would be for themselves.

Plz check this out in [CVPR 2022 Hugging Face Spaces](https://huggingface.co/spaces/CVPR/ml-talking-face)
