### ISSUE TITLE
Dear deepkyu, thanks for your remind. Is there any way that we could deploy it locally to run? Thx.

### ISSUE THREAD

**Issue by deepkyu** [deepkyu/ml-talking-face#2]
Dear deepkyu, thanks for your remind. Is there any way that we could deploy it locally to run? Thx.

_Originally posted by @datased2019 in https://github.com/deepkyu/ml-talking-face/issues/1#issuecomment-1278528483_

**Comment by deepkyu** [comment]
Hi @datased2019,

Actually, I'd like to but it is hard for me... as mentioned in [HF discussions](https://huggingface.co/spaces/CVPR/ml-talking-face/discussions/9).
The company didn't allow to open the source.

If you are stuck in re-implementing the paper, plz post an issue and I try my best to answer all the issues and share my experience.

Again, I hope you understand. Enjoy :)

**Comment by datased2019** [comment]
Hi @deepkyu 
Thx for your reply. The problem for me is talking face generation, especially the training process.

**Comment by deepkyu** [comment]
@datased2019 
Even if it is just for the talking face generation, the former company didn't allow for code to be public.
So, I'm sorry but for now there is no way to make codes of both training and inference publicly available.

**Comment by datased2019** [comment]
@deepkyu 
Understand. Thank you.
