### ISSUE TITLE
can i replace the woman to other man or child？

### ISSUE THREAD

**Issue by sunboy123** [deepkyu/ml-talking-face#3]

**Comment by sunboy123** [comment]
this tech is so cool， but i want to konw how can do my own perform video。thanks

**Comment by deepkyu** [comment]
Hi @sunboy123 ,

Thank you for being so interested in our demo!
But I'm sorry that it's impossible to generate with another person's facial video.
Our demo and study are confined to training with the dataset from a single person.
It means that we have to train models with datasets from another person.
Unfortunately, I left the company where I released this demo, and the executives have not allowed the code release for models in this demo.

Sorry again. I hope you understand.

**Comment by sunboy123** [comment]
OK， i know， i think this tech There will be a great use of users here.  thanks

**Comment by deepkyu** [comment]
Thank you for understanding.

I am planning to continue researching this task as my side project.
I'll do my best for helping you and others who are watching this demo.

Thank you again.
Hyoung-Kyu
